version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Desktop/oshan_bhagya/oshan-bhagya"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"